In [19]:
import pandas as pd
df = pd.read_csv("Sales-Export_2019-2020.csv")
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

In [22]:
df.info()
df.describe()
df.shape
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            1000 non-null   object
 1    order_value_EUR   1000 non-null   object
 2    cost              1000 non-null   float64
 3   date               1000 non-null   object
 4   category           1000 non-null   object
 5   customer_name      1000 non-null   object
 6   sales_manager      1000 non-null   object
 7   sales_rep          1000 non-null   object
 8   device_type        1000 non-null   object
 9   order_id           1000 non-null   object
dtypes: float64(1), object(9)
memory usage: 78.3+ KB

country              0
 order_value_EUR     0
 cost                0
date                 0
category             0
customer_name        0
sales_manager        0
sales_rep            0
device_type          0
order_id             0
dtype: int64

In [23]:
df.isnull().sum()

country              0
 order_value_EUR     0
 cost                0
date                 0
category             0
customer_name        0
sales_manager        0
sales_rep            0
device_type          0
order_id             0
dtype: int64

In [24]:
df.duplicated().sum()

0

In [26]:
df['date']=pd.to_datetime(df['date'],errors='coerce')

In [27]:
df['country'] = df['country'].str.lower().str.strip()
df['category'] = df['category'].str.lower().str.strip()
df['device_type'] = df['device_type'].str.lower().str.strip()

In [28]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [29]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            1000 non-null   object
 1   _order_value_eur_  1000 non-null   object
 2   _cost_             1000 non-null   float64
 3   date               1000 non-null   datetime64[ns]
 4   category           1000 non-null   object
 5   customer_name      1000 non-null   object
 6   sales_manager      1000 non-null   object
 7   sales_rep          1000 non-null   object
 8   device_type        1000 non-null   object
 9   order_id           1000 non-null   object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 78.3+ KB

,country,_order_value_eur_,_cost_,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,sweden,"17,524.02",14122.61,2020-02-12,books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,mobile,70-0511466
1,finland,"116,563.40",92807.78,2019-09-26,games,Hilll-Vandervort,Hube Corey,Wat Bowkley,mobile,28-6585323
2,portugal,"296,465.56",257480.34,2019-07-11,clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,pc,58-7703341
3,portugal,"74,532.02",59752.32,2020-04-02,beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,pc,14-6700183
4,spain,"178,763.42",146621.76,2019-12-22,games,Johns and Sons,Emalia Dinse,Bertha Walbrook,tablet,15-8765160

In [30]:
df.duplicated().sum()

0

In [31]:
df['country'] = df['country'].str.lower().str.strip()
df['category'] = df['category'].str.lower().str.strip()
df['device_type'] = df['device_type'].str.lower().str.strip()
df['customer_name'] = df['customer_name'].str.strip()

In [32]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [33]:
df.info()
df.head()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            1000 non-null   object
 1   _order_value_eur_  1000 non-null   object
 2   _cost_             1000 non-null   float64
 3   date               1000 non-null   datetime64[ns]
 4   category           1000 non-null   object
 5   customer_name      1000 non-null   object
 6   sales_manager      1000 non-null   object
 7   sales_rep          1000 non-null   object
 8   device_type        1000 non-null   object
 9   order_id           1000 non-null   object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 78.3+ KB

              _cost_                           date
count    1000.000000                           1000
mean    94369.310990  2020-01-01 05:41:16.799999744
min     12113.680000            2019-01-02 00:00:00
25%     54247.957500            2019-06-30 18:00:00
50%     87094.760000            2020-01-05 00:00:00
75%    125570.837500            2020-06-26 00:00:00
max    304701.430000            2020-12-30 00:00:00
std     51540.020934                            NaN

In [38]:
df.to_csv("cleaned_dataset.csv",index=False)

In [39]:
import os
os.getcwd()

'C:\\Users\\Lenovo'